config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    resources :users, only: [:new, :create, :show]
    resources :posts, only: [:show, :new, :create] do
      collection do
        get "/sub_topics", to: "posts#load_subtopic"
      end
      resources :comments, only: [:new, :create]
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :activity, polymorphic: true
  belongs_to :owner, class_name: User.name
  belongs_to :receiver, class_name: User.name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader,
    mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :parent_comment, class_name: Comment.name,
                            optional: true

  has_many :sub_comments, class_name: Comment.name,
                        foreign_key: :comment_id
  has_many :activities

  validates :content, presence: true
  scope :root_comments, ->{where comment_id: nil}
  scope :date_descending, ->{order created_at: :desc}
  delegate :name, to: :user, prefix: :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments
  has_many :activities
  enum status: {approved: 1, rejected: 0}
  validates :subject, presence: true
  validates :topic_id, presence: true
  validates :content, presence: true,
                      length: {maximum: Settings.post.content.minimum}
  delegate :name, to: :user, prefix: :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  has_many :sub_topics, class_name: Topic.name,
                      foreign_key: :topic_id

  belongs_to :parent_topic, class_name: Topic.name, optional: true
  scope :root_topics, ->{where topic_id: nil}
  scope :all_sub_topics_by_id, ->(id){where topic_id: id}
  scope :select_id_content, ->{select :id, :content}
  scope :alphabet_content, ->{order :content}
end

app/models/user.rb
class User < ApplicationRecord
  before_save{email.downcase!}

  has_many :activities
  has_many :posts
  has_many :comments
  has_many :owner, class_name: Activity.name,
                    foreign_key: :onwer_id,
                    dependent: :destroy
  has_many :receiver, class_name: Activity.name,
                    foreign_key: :receiver_id,
                    dependent: :destroy

  enum role: {admin: 1, user: 0}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            length: {maximum: Settings.user_password.maximum},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :name, presence: true,
            length: {
              maximum: Settings.user_name.maximum,
              minimum: Settings.user_name.minimum
            }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :load_topic

  include SessionsHelper
  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end

  def load_topic
    @parent_topics = Topic.root_topics
                          .select_id_content
                          .alphabet_content
                          .eager_load(:sub_topics)
  end

  def check_login
    return if log_in?
    store_location
    flash[:danger] = t "posts.new.require_login"
    redirect_to login_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_login, only: :create

  def create
    @comment = current_user.comments.build comment_params
    if @comment.save
      flash[:success] = t "comment.create.comment_sucess"
    else
      flash[:danger] = t "comment.create.comment_error"
    end
    respond_to do |format|
      format.html{redirect_back fallback_location: root_path}
      format.js
    end
  end

  private

  def comment_params
    params[:comment][:post_id] = params[:post_id]
    params.require(:comment).permit :content, :post_id, :comment_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, only: :show
  before_action :load_root_topics, only: :new
  before_action :check_login, only: [:new, :create]
  before_action :build_comment, only: :show

  def index; end

  def show
    @comments = @post
                .comments
                .root_comments
                .eager_load(:sub_comments, :user)
                .date_descending
                .paginate page: params[:page],
                          per_page: Settings.comment.paginate
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      flash[:success] = t "posts.new.create_sucess"
      redirect_to @post
    else
      flash.now[:danger] = "posts.new.create_fail"
      load_root_topics
      render :new
    end
  end

  def load_subtopic
    @sub_topics = Topic.all_sub_topics_by_id(params[:id]).pluck :content, :id
    respond_to do |format|
      format.html
      format.json{render json: {sub_topics: @sub_topics}}
    end
  end

  private

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post
    flash[:danger] = t ".post_not_found"
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit :subject, :content, :topic_id
  end

  def load_root_topics
    @root_topics = Topic.root_topics.pluck :content, :id
  end

  def build_comment
    @comment = @post.comments.build
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :load_user, only: :create

  def new; end

  def create
    if @user.authenticate params[:session][:password]
      flash[:success] = t "sessions.new.success"
      log_in @user
      redirect_back_or @user
    else
      flash[:danger] = t "sessions.new.password_wrong"
      render :new
    end
  end

  private

  def load_user
    @user = User.find_by email: params[:session][:email]
    return if @user
    flash[:danger] = t "sessions.new.email_wrong"
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "users.new.regis_success"
      redirect_back fallback_location: root_path
    else
      flash[:success] = "users.new.regis_fail"
      render :new
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit :email, :name,
      :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def log_in?
    current_user.present?
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/views/comments/_comment.html.erb
<div class="d-flex flex-row-reverse w-100">
  <div class="col-md-10 col-sm-10">
    <article class="row one-comment">
      <div class="col-md-2 col-sm-2 hidden-xs">
        <figure class="thumbnail">
          <%= image_tag "review/user-avatar-placeholder.png", class: "img-responsive" %>
        </figure>
      </div>
      <div class="col-md-10 col-sm-10">
        <div class="panel panel-default arrow left">
          <div class="panel-body">
            <header class="text-left">
              <div class="comment-user text-white">
                <i class="fa fa-user text-white"></i>
                <%= comment.user_name %>
              </div>
              <time class="comment-date text-white">
                <i class="fa fa-clock-o text-white"></i>
                <%= t "posts.show.time", name: time_ago_in_words(comment.created_at) %>
              </time>
            </header>
            <div class="comment-post">
              <p class="text-white">
                <%= comment.content %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>

app/views/comments/create.js.erb
$('.subcomment').append('<%= j render "comments/comment", comment: @comment %>');
$('.reset-text').val("");

app/views/layouts/_error.html.erb
<section class="error-hide">
  <% flash.each do |key, value| %>
    <div class="row justify-content-center text-center">
      <div class="alert alert-<%= key %> w-100">
        <%= value %>
      </div>
    </div>
  <% end %>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer-section">
  <div class="container">
    <div class="footer-left-pic">
      <%= image_tag("footer-left-pic.png", alt: "#") %>
    </div>
    <div class="footer-right-pic">
      <%= image_tag("footer-right-pic.png", alt: "#") %>
    </div>
    <%= link_to "#", class: "footer-logo" do %>
      <%= image_tag("logo.png", alt: "#") %>
    <% end %>
    <ul class="main-menu footer-menu">
      <li><%= link_to t(".home"), "#" %></li>
      <li><%= link_to t(".home"), "#" %></li>
      <li><%= link_to t(".home"), "#" %></li>
      <li><%= link_to t(".home"), "#" %></li>
      <li><%= link_to t(".home"), "#" %></li>
    </ul>
    <div class="footer-social d-flex justify-content-center">
      <%= link_to "#" do %>
        <i class="fa fa-pinterest"></i>
      <% end %>
      <%= link_to "#" do %>
        <i class="fa fa-facebook"></i>
      <% end %>
      <%= link_to "#" do %>
        <i class="fa fa-dribbble"></i>
      <% end %>
      <%= link_to "#" do %>
        <i class="fa fa-twitter"></i>
      <% end %>
      <%= link_to "#" do %>
        <i class="fa fa-behance"></i>
      <% end %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header-section">
  <div class="header-warp">
    <div class="header-social d-flex justify-content-end">
      <p><%= t ".language" %></p>
      <%= link_to t(".english"), locale:"en" %>
      <%= link_to t(".vietnamese"), locale:"vi" %>
    </div>
    <div class="header-bar-warp d-flex">
      <%= link_to root_path, class: "site-logo" do %>
        <%= image_tag("logo.png", alt: t(".Gamecommunity")) %>
      <% end %>
      <nav class="top-nav-area w-100">
        <div class="user-panel">
          <% if log_in? %>
            <%= t(".hello")%> <%=link_to current_user.name, "#" %>
            |<%= link_to "#" do %>
               logout <i class="text-white fa fa-power-off"></i>
            <% end %>

          <% else %>
            <%= link_to t(".login"), login_path %>
            / <%= link_to t(".register"), new_user_path %>
          <% end %>
        </div>
        <ul class="main-menu primary-menu">
          <li><%= link_to t(".home"), "#" %></li>
          <% @parent_topics.each do |parent| %>
            <li><%= link_to parent.content, "#" %>
              <ul class="sub-menu">
              <% parent.sub_topics.each do |topic| %>
                <li><%= link_to topic.content, "#" %></li>
              <% end %>
              </ul>
            </li>
          <% end %>
          <li><%= link_to t(".news"), "#" %></li>
          <li><%= link_to t(".contact"), "#" %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_pagetop.html.erb
<section class="page-top-section set-bg" data-setbg="/assets/page-top-bg/2.jpg">
  <div class="page-info">
    <h2><%= yield(:title) %></h2>
    <div class="site-breadcrumb">
      <a href=""><%= t ".home" %></a>  /
      <span><%= yield(:subtitle_lv1) %></span> /
      <span><%= yield(:subtitle_lv2) %></span>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t ".title" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/posts/new.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<% provide(:subtitle_lv1, t("layouts.pagetop.create_post")) %>
<section class="games-single-page">
  <div class="container">
    <%= render "layouts/pagetop" %>
    <div class="row">
      <div class="col-xl-9 col-lg-8 col-md-7 game-single-content">
        <%= bootstrap_form_for(@post) do |f| %>
          <%= f.text_field :subject, label: t(".title"), label_class: "text-white"
           %>
          <div class="form-group">
            <label class="text-white"><%= t ".root topic" %></label>
            <%= select_tag :parent, options_for_select(@root_topics),
            {include_blank: true, class: "form-control", id: "root_topic"} %>
          </div>
          <div class="form-group">
            <label class="text-white"><%= t ".sub_topic" %></label>
            <div id="subtopics">
              <%= select_tag :topic_id, {},class: "form-control", id: "root_topic" %>
            </div>
          </div>
          <%= f.cktext_area :content, ckeditor: { language: I18n.locale} %>
          <%= f.submit t(".create") %>
        <% end %>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-5 sidebar game-page-sideber">
        <div id="stickySidebar">
          <div class="widget-item">
            <div class="rating-widget">
              <h4 class="widget-title"><%= t ".suggest" %></h4>
              <!-- This area for suggest item -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<% provide(:subtitle_lv1, @post.topic.content) %>
<% provide(:title, @post.subject) %>
<% provide(:subtitle_lv2, @post.subject) %>
<section class="games-single-page">
  <div class="container">
    <%= render "layouts/pagetop" %>
    <div class="row">
      <div class="col-xl-9 col-lg-8 col-md-7 game-single-content">
        <h2 class="gs-title"><%= @post.subject %></h2>
        <div class="gs-meta">
          <%= t "posts.show.time", name: time_ago_in_words(@post.created_at) %>
          <%= t ".in" %> <%= link_to @post.topic.content, "#" %>
        </div>
        <p class="text-white"><%= @post.content.html_safe %></p>
        <div class="geme-social-share pt-5 d-flex">
          <p><%= t ".share" %></p>
          <%= link_to "#" do %>
            <i class="fa fa-pinterest"></i>
          <% end %>
          <%= link_to "#" do %>
            <i class="fa fa-facebook"></i>
          <% end %>
          <%= link_to "#" do %>
            <i class="fa fa-dribbble"></i>
          <% end %>
            <%= link_to "#" do %>
          <i class="fa fa-twitter"></i>
          <% end %>
          <%= link_to "#" do %>
            <i class="fa fa-behance"></i>
          <% end %>
        </div>
        <section class="game-author-section">
          <div class="container">
            <div class="game-author-pic set-bg" data-setbg="/assets/author.jpg"></div>
            <div class="game-author-info">
              <h4><%= t ".write_by" %> <%= @post.user_name %></h4>
            </div>
          </div>
        </section>
        <div class="container">
          <div class="row">
            <div class="col-md-10">
              <section class="comment-list">
                <div class="reply-post w-100">
                  <%= render "layouts/error" %>
                  <h3 class="page-header text-white"><%= t ".write_a_comments" %></h3>
                  <%= bootstrap_form_for [@post, @comment] do |f| %>
                    <%= f.text_field :content, hide_label: true %>
                    <%= f.submit t(".comment") %>
                  <% end %>
                </div>
                <h2 class="page-header text-white"><%= t ".comment" %></h2>
                <% @comments.each do |comment| %>
                  <article class="row one-comment">
                    <div class="col-md-2 col-sm-2 hidden-xs">
                      <figure class="thumbnail">
                        <%= image_tag "review/user-avatar-placeholder.png", class: "img-responsive" %>
                      </figure>
                    </div>
                    <div class="col-md-10 col-sm-10">
                      <div class="panel panel-default arrow left">
                        <div class="panel-body">
                          <header class="text-left">
                            <div class="comment-user text-white">
                              <i class="fa fa-user text-white"></i>
                              <%= comment.user.name %>
                            </div>
                            <time class="comment-date text-white">
                              <i class="fa fa-clock-o text-white"></i>
                              <%= t "posts.show.time", name: time_ago_in_words(comment.created_at) %>
                            </time>
                          </header>
                          <div class="comment-post">
                            <p class="text-white">
                              <%= comment.content %>
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <%= render partial: "comments/comment",
                      collection: comment.sub_comments, as: :comment %>
                    <div class="subcomment"></div>
                    <!-- Form reply comment -->
                    <div class="d-flex flex-row-reverse w-100">
                      <div class="col-md-10 col-sm-10">
                        <article class="row one-comment">
                          <%= bootstrap_form_for [@post, @comment], remote: true do |f| %>
                            <%= f.text_field :content, hide_label: true, class: "form-control reset-text" %>
                            <p class="btn btn-default btn-sm text-white text-right">
                              <i class="fa fa-reply text-white"></i>
                              <%= f.submit t(".reply"), class: "btn btn-secondary button-custom" %>
                            </p>
                          <% end %>
                        </article>
                      </div>
                    </div>
                    <!-- End form reply comment -->
                  </article>
                <% end %>
              </section>
              <%= will_paginate @comments, page_links: false %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-5 sidebar game-page-sideber">
        <div id="stickySidebar">
          <div class="widget-item">
            <div class="rating-widget">
              <h4 class="widget-title"><%= t ".suggest" %></h4>
              <!-- This area for suggest item -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/contact.html.erb
<section class="contact-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 order-1 order-lg-2 contact-text text-white">
        <h3><%= t ".title" %></h3>
        <p><%= t ".content" %></p>
        <div class="cont-info">
          <div class="ci-icon">
            <%= image_tag("icons/location.png", alt: "#") %>
            <div class="ci-text">Main Str, no 23, New York</div>
          </div>
          <div class="cont-info">
            <div class="ci-icon">
              <%= image_tag("icons/phone.png", alt: "#") %>
              <div class="ci-text">+546 990221 123</div>
            </div>
            <div class="cont-info">
              <div class="ci-icon">
               <%= image_tag("icons/mail.png", alt: "#") %>
               <div class="ci-text">hosting@contact.com</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
 </div>
</section>

app/views/static_pages/index.html.erb
<section class="hero-section overflow-hidden">
  <div class="hero-slider owl-carousel">
    <div class="hero-item set-bg d-flex align-items-center justify-content-center text-center" data-setbg="assets/slider-bg-1.jpg">
      <div class="container">
        <h2><%= t ".title" %></h2>
        <p><%= t ".content" %></p>
        <%= link_to "#", class: "site-btn" do %>
          <%= t(".read_more") %>
          <%= image_tag("icons/double-arrow.png", alt: "#") %>
        <% end %>
      </div>
    </div>
    <div class="hero-item set-bg d-flex align-items-center justify-content-center text-center" data-setbg="assets/slider-bg-2.jpg">
      <div class="container">
        <h2><%= t ".title" %></h2>
        <p><%= t ".content" %></p>
        <%= link_to "#", class: "site-btn" do %>
          <%= t(".read_more") %>
          <%= image_tag("icons/double-arrow.png", alt: "#") %>
        <% end %>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end-->

<!-- Intro section -->
<section class="intro-section">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="intro-text-box text-box text-white">
          <div class="top-meta">11.11.18  /  in <%= link_to t(".reviews"), "#" %></div>
          <h3><%= t ".title" %></h3>
          <p><%= t ".content" %></p>
          <%= link_to "#", class: "read-more" do %>
            <%= t(".read_more") %>
            <%= image_tag("icons/double-arrow.png", alt: "#") %>
          <% end %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="intro-text-box text-box text-white">
          <div class="top-meta">11.11.18  /  in <%= link_to t(".reviews"), "#" %></div>
          <h3><%= t ".title" %></h3>
          <p><%= t ".content" %></p>
          <%= link_to "#", class: "read-more" do %>
            <%= t(".read_more") %>
            <%= image_tag("icons/double-arrow.png", alt: "#") %>
          <% end %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="intro-text-box text-box text-white">
          <div class="top-meta">11.11.18  /  in <%= link_to t(".reviews"), "#" %></div>
          <h3><%= t ".title" %></h3>
          <p><%= t ".content" %></p>
          <%= link_to "#", class: "read-more" do %>
            <%= t(".read_more") %>
            <%= image_tag("icons/double-arrow.png", alt: "#") %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Intro section end -->

<!-- Blog section -->
<section class="blog-section spad">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 col-lg-8 col-md-7">
        <div class="section-title text-white">
          <h2><%= t ".lastest_news" %></h2>
        </div>
        <ul class="blog-filter">
          <li><%= link_to t(".online"), "#" %></li>
          <li><%= link_to t(".online"), "#" %></li>
          <li><%= link_to t(".online"), "#" %></li>
          <li><%= link_to t(".online"), "#" %></li>
        </ul>
        <div class="blog-item">
          <div class="blog-thumb">
            <%= image_tag("blog/1.jpg", alt: "#") %>
          </div>
          <div class="blog-text text-box text-white">
            <div class="top-meta">11.11.18  /  in <%= link_to t(".game"), "#" %></div>
            <h3><%= t ".title" %></h3>
            <p><%= t ".content" %></p>
            <%= link_to "#", class: "read-more" do %>
              <%= t(".read_more") %>
              <%= image_tag("icons/double-arrow.png", alt: "#") %>
            <% end %>
          </div>
        </div>
        <div class="blog-item">
          <div class="blog-thumb">
            <%= image_tag("blog/2.jpg", alt: "#") %>
          </div>
          <div class="blog-text text-box text-white">
            <div class="top-meta">11.11.18  /  in <%= link_to t(".game"), "#" %></div>
            <h3><%= t ".title" %></h3>
            <p><%= t ".content" %></p>
            <%= link_to "#", class: "read-more" do %>
              <%= t(".read_more") %>
              <%= image_tag("icons/double-arrow.png", alt: "#") %>
            <% end %>
          </div>
        </div>
        <div class="blog-item">
          <div class="blog-thumb">
            <%= image_tag("blog/3.jpg", alt: "#") %>
          </div>
          <div class="blog-text text-box text-white">
            <div class="top-meta">11.11.18  /  in <%= link_to t(".game"), "#" %></div>
            <h3><%= t ".title" %></h3>
            <p><%= t ".content" %></p>
            <%= link_to "#", class: "read-more" do %>
              <%= t(".read_more") %>
              <%= image_tag("icons/double-arrow.png", alt: "#") %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-lg-4 col-md-5 sidebar">
        <div id="stickySidebar">
          <div class="widget-item">
            <h4 class="widget-title">Trending</h4>
            <div class="trending-widget">
              <div class="tw-item">
                <div class="tw-thumb">
                  <%= image_tag("blog-widget/1.jpg", alt: "#") %>
                </div>
                <div class="tw-text">
                  <div class="tw-meta">11.11.18  /  in <%= link_to t(".games"), "#" %></div>
                  <h5><%= t ".title" %></h5>
                </div>
              </div>
              <div class="tw-item">
                <div class="tw-thumb">
                  <%= image_tag("blog-widget/2.jpg", alt: "#") %>
                </div>
                <div class="tw-text">
                  <div class="tw-meta">11.11.18  /  in <%= link_to t(".games"), "#" %></div>
                  <h5><%= t ".title" %></h5>
                </div>
              </div>
            </div>
          </div>
          <div class="widget-item">
            <div class="categories-widget">
              <h4 class="widget-title"><%= t ".categories" %></h4>
              <ul>
                <li><%= link_to t(".games"), "#" %></li>
                <li><%= link_to t(".games"), "#" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Blog section end -->

app/views/users/_form.html.erb
<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label t("users.new.name"), class: "control-label text-white" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.new.email"), class: "control-label text-white" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.new.password"), class: "control-label text-white" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.new.password_confirm"), class: "control-label text-white" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit t("users.new.register"), class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, t(".register")) %>
<%= render "layouts/pagetop" %>
<section class="blog-section spad">
  <div class="container margin-top">
    <div class="row align-items-center justify-content-center text-center">
      <h1 class="title text-white"><%= t ".register" %></h1>
    </div>
    <%= render "layouts/error" %>
    <div class="row align-items-center justify-content-center">
      <div class="col-lg-offset-3 col-lg-6">
        <%= render "form" %>
      </div>
    </div>
  </div>
</section>